apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: idp-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: idp-platform
    idp.platform/tier: gitops
spec:
  description: Local-first IDP platform GitOps project

  sourceRepos:
    - https://github.com/goozdu12/cloud-native-idp-platform.git
    - https://prometheus-community.github.io/helm-charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'