apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-smoke
  namespace: apps
  labels:
    app.kubernetes.io/name: vault-auth-smoke
    app.kubernetes.io/part-of: idp-platform
    idp.platform/tier: secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-token-reviewer
  labels:
    app.kubernetes.io/name: vault-token-reviewer
    app.kubernetes.io/part-of: idp-platform
    idp.platform/tier: secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
