apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-grpc
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: idp-platform
    idp.platform/tier: workload
spec:
  project: idp-platform

  source:
    repoURL: https://github.com/goozdu12/cloud-native-idp-platform.git
    targetRevision: main
    path: charts/demo-grpc
    helm:
      releaseName: demo-grpc
      values: |
        image:
          repository: ghcr.io/goozdu12/cloud-native-idp-platform/demo-grpc
          tag: sha-4398e39
          pullPolicy: IfNotPresent

        imagePullSecrets:
          - name: ghcr-demo-grpc-pull

        env:
          SERVICE_NAME: demo-grpc
          APP_VERSION: sha-4398e39

        service:
          port: 50051

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
