apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: idp-platform
    idp.platform/tier: security
spec:
  project: idp-platform
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.8.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: kyverno
        app.kubernetes.io/part-of: idp-platform
        idp.platform/tier: security
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/audit: restricted
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
