apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: idp-platform
    idp.platform/tier: security
spec:
  project: idp-platform
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.8.1
    helm:
      values: |
        config:
          preserve: false
        webhookLabels:
          app.kubernetes.io/managed-by: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: kyverno
        app.kubernetes.io/part-of: idp-platform
        idp.platform/tier: security
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/audit: restricted
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
