apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: idp-platform
    idp.platform/tier: observability
spec:
  project: idp-platform
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 17.4.7
      helm:
        releaseName: loki
        valueFiles:
          - $values/platform/helm-values/loki-values.yaml
    - repoURL: https://github.com/goozdu12/cloud-native-idp-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
