apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-namespaces
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: idp-platform
    idp.platform/tier: gitops
spec:
  project: idp-platform
  source:
    repoURL: https://github.com/goozdu12/cloud-native-idp-platform.git
    targetRevision: main
    path: platform/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
---