apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies
  namespace: argocd
  labels:
    app.kubernetes.io/name: network-policies
    app.kubernetes.io/part-of: idp-platform
    idp.platform/tier: security
spec:
  project: idp-platform
  source:
    repoURL: https://github.com/goozdu12/cloud-native-idp-platform.git
    targetRevision: main
    path: platform/security/network-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
